# Generated by Django 3.2.9 on 2021-11-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compozitii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=150)),
                ('an_aparitie', models.SmallIntegerField()),
                ('gen', models.CharField(max_length=45)),
                ('gama', models.CharField(max_length=15)),
                ('nr_instrumente', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compozitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=100)),
                ('stil', models.CharField(max_length=45)),
                ('tara_origine', models.CharField(max_length=45)),
                ('data_nasterii', models.DateField()),
                ('data_mortii', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cataloage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=15)),
                ('id_compozitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzica_clasica.compozitii')),
                ('id_compozitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzica_clasica.compozitori')),
            ],
        ),
    ]
