# Generated by Django 3.2.9 on 2021-11-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzica_clasica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compozitii',
            name='gama',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compozitii',
            name='nr_instrumente',
            field=models.SmallIntegerField(null=True),
        ),
    ]
