# Generated by Django 3.2.9 on 2021-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzica_clasica', '0002_auto_20211104_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compozitii',
            name='gama',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compozitii',
            name='nr_instrumente',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
