# Generated by Django 3.2.9 on 2021-11-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzica_clasica', '0003_auto_20211104_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cataloage',
            old_name='id_compozitie',
            new_name='compozitie',
        ),
        migrations.RenameField(
            model_name='cataloage',
            old_name='id_compozitor',
            new_name='compozitor',
        ),
    ]
