# Generated by Django 3.2.9 on 2021-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzica_clasica', '0004_auto_20211104_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compozitii',
            name='gama',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compozitii',
            name='nr_instrumente',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='compozitori',
            name='data_mortii',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
